/**
 * ⚠️  本文件由 Scripts/genEventTypes.ts 自动生成，禁止手动修改。
 * 后端 SSOT：Src/Services/EventBus/eventTypes.ts
 * 构建命令：npx tsx Scripts/genEventTypes.ts
 */

export const EventType = {
  TASK_RECEIVED: 'task:received' as const,
  TASK_DECOMPOSED: 'task:decomposed' as const,
  TASK_ASSIGNED: 'task:assigned' as const,
  TASK_STARTED: 'task:started' as const,
  TASK_PROGRESS: 'task:progress' as const,
  TASK_COMPLETED: 'task:completed' as const,
  TASK_FAILED: 'task:failed' as const,
  AGENT_RECRUITED: 'agent:recruited' as const,
  AGENT_READY: 'agent:ready' as const,
  AGENT_EXPELLED: 'agent:expelled' as const,
  AGENT_DESTROYED: 'agent:destroyed' as const,
  AGENT_STREAM_CHUNK: 'agent:stream_chunk' as const,
  AGENT_STREAM_END: 'agent:stream_end' as const,
  AGENT_CHAT_MESSAGE: 'agent:chat_message' as const,
  TOKEN_CONSUMED: 'token:consumed' as const,
  TOKEN_EARNED: 'token:earned' as const,
  TOKEN_DISTRIBUTED: 'token:distributed' as const,
  TAX_PAID: 'token:tax_paid' as const,
  TAX_RATE_UPDATED: 'token:tax_rate_updated' as const,
  WALLET_FROZEN: 'token:wallet_frozen' as const,
  WALLET_UNFROZEN: 'token:wallet_unfrozen' as const,
  TOKEN_CONFISCATED: 'token:confiscated' as const,
  INSUFFICIENT_BALANCE: 'token:insufficient_balance' as const,
  LEDGER_MISMATCH: 'token:ledger_mismatch' as const,
  CONFLICT_DETECTED: 'arbitration:conflict_detected' as const,
  ARBITRATION_FILED: 'arbitration:filed' as const,
  SUSPEND_AND_NOTIFY: 'arbitration:suspend_and_notify' as const,
  ARBITRATION_VERDICT: 'arbitration:verdict' as const,
  RESTORATION_ACK: 'arbitration:restoration_ack' as const,
  KNOWLEDGE_CONSOLIDATION: 'arbitration:knowledge_consolidation' as const,
  ARBITRATION_DEADLOCK: 'arbitration:deadlock' as const,
  ARBITRATOR_POOL_RESIZED: 'arbitration:pool_resized' as const,
  RULE_UPDATED: 'regulation:rule_updated' as const,
  BROADCAST_MESSAGE: 'regulation:broadcast' as const,
  EMERGENCY_INTERVENTION: 'regulation:emergency' as const,
  ANOMALY_DETECTED: 'audit:anomaly_detected' as const,
  AUDIT_COMPLETED: 'audit:completed' as const,
  PATROL_REPORT: 'audit:patrol_report' as const,
  MEMORY_WRITTEN: 'memory:written' as const,
  MEMORY_SUPERSEDED: 'memory:superseded' as const,
  MEMORY_VERSION_CONFLICT: 'memory:version_conflict' as const,
  MEMORY_SELF_REINFORCING: 'memory:self_reinforcing' as const,
  LOOP_STARTED: 'loop:started' as const,
  LOOP_COMPLETED: 'loop:completed' as const,
  LOOP_ABORTED: 'loop:aborted' as const,
  BUDGET_WARMING: 'loop:budget_warming' as const,
  BUDGET_SOFT_REACHED: 'loop:budget_soft_reached' as const,
  BUDGET_HARD_REACHED: 'loop:budget_hard_reached' as const,
  NO_PROGRESS_STAGNATED: 'loop:no_progress_stagnated' as const,
  ACTION_FINGERPRINT_DUPLICATE: 'loop:action_fingerprint_duplicate' as const,
  APPROVAL_REQUESTED: 'loop:approval_requested' as const,
  APPROVAL_DECIDED: 'loop:approval_decided' as const,
  APPROVAL_TIMEOUT_REJECTED: 'loop:approval_timeout_rejected' as const,
  VERIFIER_FAILED: 'loop:verifier_failed' as const,
  CONTEXT_COMPRESSED: 'loop:context_compressed' as const,
  EFFECT_UNKNOWN: 'durable:effect_unknown' as const,
  LOOP_SUSPENDED: 'durable:loop_suspended' as const,
  LOOP_RESUMED: 'durable:loop_resumed' as const,
  RECOVERY_HUMAN_REQUIRED: 'durable:recovery_human_required' as const,
  ARTIFACT_DRIFT_DETECTED: 'durable:artifact_drift_detected' as const,
  SHUTDOWN_FLUSH_TIMEOUT: 'system:shutdown_flush_timeout' as const,
  CONFIG_RELOAD_FAILED: 'system:config_reload_failed' as const,
} as const;

export type EventTypeValue = typeof EventType[keyof typeof EventType];
